### PR TITLE
Energy plots for butterfly case

### PR DESCRIPTION
**Pull request by tp5uiuc**
Having energy plots is a useful diagnostic to test the accuracy of our Cosserat rod implementation along with the time-stepping algorithm.

### CODE REVIEW

**Review by armantekinalp — COMMENTED** [review]
LGTM. 

Why do you save plots as pdf instead of png? Is there any reason

**Comment by tp5uiuc** [comment]
The CI builds fail on an unrelated test case. Is this a known issue?

**Comment by tp5uiuc** [comment]
> LGTM.
> 
> Why do you save plots as pdf instead of png? Is there any reason

No reason, the last plot (`butterfly.pdf`) was also saved as pdf, hence I just used the same.

**Comment by armantekinalp** [comment]
Also can we change PR direction instead of `master` to `update-v0.2.1` ? We will do new realease soon. What do you think @skim0119

**Comment by skim0119** [comment]
It is probably safer to merge into the update branch.

**Review by skim0119 — APPROVED** [review]
LGTM

**Pull request merged**
