### PR TITLE
Update contact model

### PR DESCRIPTION
**Pull request by armantekinalp**
Adding self contact and rod-rod contact models

solves #31

### CODE REVIEW

**Comment by skim0119** [comment]
@armantekinalp Could you add the new version and explain changes in [release](https://github.com/GazzolaLab/PyElastica/blob/update-v0.2.1/RELEASE.md)?

**Comment by armantekinalp** [comment]
Here are the solenoid result:

https://user-images.githubusercontent.com/53585636/148668212-820c7dc9-cc05-400b-94db-151782b0bec6.mp4

And for plectonemes


https://user-images.githubusercontent.com/53585636/148668219-aba15381-9a08-4236-98e5-1cbb85f35e0b.mp4

**Comment by armantekinalp** [comment]
I think after the review we can merge @skim0119

**Review by skim0119 — APPROVED** [review]
LGTM. We should probably address code coverage at some point.

**Pull request merged**
