### PR TITLE
Contact Module Documentation

### PR DESCRIPTION
**Pull request by Ali-7800**
Last contact module PR mentioned in [Issue](https://github.com/GazzolaLab/PyElastica/issues/113) 
This PR includes:

- Updated documentation to include new contact module and surface class
- Update examples README for changes in this update.
- [Refactor: function documentations for NoForcing and FreeJoint](https://github.com/GazzolaLab/PyElastica/issues/287)

### CODE REVIEW

**Review by armantekinalp — APPROVED** [review]
LGTM

**Comment by skim0119** [comment]
Push to doc_patch branch

**Review by ilianasiriziba — APPROVED** [review]

**Comment by armantekinalp** [comment]
@skim0119 can you lgtm

**Review by skim0119 — APPROVED** [review]
LG

**Pull request merged**
