### PR TITLE
(#80) node to element interpolation fix

### LINKED ISSUE #80: Converting nodal velocities to element velocities
In PyElastica we store `velocity` on nodes and for some computations (i.e. rod damping, plane damping or stokes flow) we have to convert `velocity` from `nodes` to `elements`. Currently we are averaging the neigboring node velocity to compute element velocity using the following function.

https://github.com/GazzolaLab/PyElastica/blob/fee87b9da22e310ff925c16fdc839bf8405c51a4/elastica/interaction.py#L664-L703

Although this function is correct for uniform rods (uniform cross-section, element length and density) for tapered rods, momentum is not conserved since neighboring node masses are not the same. Thus, we have to first compute the total momentum of element and divide by the element mass to compute element velocity. 

**How to fix** : 

1. Use the following function to compute element velocities

``` python

def node_to_element_velocity(mass, velocity_collection):
    """
    """
    n_elem = velocity_collection.shape[1] - 1
    element_velocity = np.empty((3, n_elem))
    for k in range(n_elem):
        element_velocity[0, k] = (
            mass[k+1] * velocity_collection[0, k + 1] + mass[k] * velocity_collection[0, k]
        )
        element_velocity[1, k] = (
            mass[k+1] * velocity_collection[1, k + 1] + mass[k] * velocity_collection[1, k]
        )
        element_velocity[2, k] =(
            mass[k+1] * velocity_collection[2, k + 1] + mass[k] * velocity_collection[2, k]
        )
        element_velocity[:,k] /= (mass[k+1] + mass[k])


    return element_velocity

```

2. Rename the function `node_to_element_pos_or_vel` as `node_to_element_position`, since this will be only used to compute the element positions.

### PR DESCRIPTION
**Pull request by bhosale2**
Fixes #80, by

1. Adding momentum conserving node-to-element interpolation for velocity.
2. Renaming older node-to-element interpolation as to be used for position.
3. Specifically naming the node-to-element interpolation used for mass/forces (edge special treatment).

@armantekinalp I ran the snake and flagella, and they produce results as expected.

### CODE REVIEW

**Comment by skim0119** [comment]
@bhosale2 Instead of renaming, can you make an alias and leave a deprecation note?

**Comment by bhosale2** [comment]
@skim0119 per discussion with @armantekinalp in aacc827:

1. For the pure renaming, as per your suggestion I have added an alias with a deprecation warning.
2. For the velocity interpolation, the function signature and computation itself change, so to avoid the users using the incorrect version, we now raise a `NotImplementedError` in the old version, with reference to the correct versions in the error message.

**Comment by armantekinalp** [comment]
Should we add tests for depreciated functions to keep coverage at the same level. What do you think @skim0119 , @bhosale2

**Comment by skim0119** [comment]
I'm adding little more info for the deprecation note.

**Comment by skim0119** [comment]
@armantekinalp 
Coverage is not working. Can you double check the token?
```
Codecov report uploader 0.2.3
[20[22](https://github.com/GazzolaLab/PyElastica/runs/6693471477?check_suite_focus=true#step:13:23)-06-01T16:20:59.822Z] ['info'] => Project root located at: /home/runner/work/PyElastica/PyElastica
[2022-06-01T16:20:59.8[23](https://github.com/GazzolaLab/PyElastica/runs/6693471477?check_suite_focus=true#step:13:24)Z] ['info'] -> No token specified or token is empty
[2022-06-01T16:20:59.973Z] ['info'] Searching for coverage files...
[2022-06-01T16:20:59.998Z] ['info'] Warning: Some files located via search were excluded from upload.
[2022-06-01T16:20:59.998Z] ['info'] If Codecov did not locate your files, please review https://docs.codecov.com/docs/supported-report-formats
[2022-06-01T16:20:59.998Z] ['error'] There was an error running the uploader: No coverage files located, please try use `-f`, or change the project root with `-R`
```

**Comment by armantekinalp** [comment]
It is working now, I updated the secret token

```
Codecov report uploader 0.2.3
[23](https://github.com/GazzolaLab/PyElastica/runs/6696748680?check_suite_focus=true#step:13:24)
[2022-06-01T19:50:23.533Z] ['info'] => Project root located at: /home/runner/work/PyElastica/PyElastica
[24](https://github.com/GazzolaLab/PyElastica/runs/6696748680?check_suite_focus=true#step:13:25)
[2022-06-01T19:50:23.535Z] ['info'] -> No token specified or token is empty
[25](https://github.com/GazzolaLab/PyElastica/runs/6696748680?check_suite_focus=true#step:13:26)
[2022-06-01T19:50:23.747Z] ['info'] Running coverage xml...
[26](https://github.com/GazzolaLab/PyElastica/runs/6696748680?check_suite_focus=true#step:13:27)
[2022-06-01T19:50:24.794Z] ['info'] Searching for coverage files...
[27](https://github.com/GazzolaLab/PyElastica/runs/6696748680?check_suite_focus=true#step:13:28)
[2022-06-01T19:50:24.865Z] ['info'] Warning: Some files located via search were excluded from upload.
[28](https://github.com/GazzolaLab/PyElastica/runs/6696748680?check_suite_focus=true#step:13:29)
[2022-06-01T19:50:24.865Z] ['info'] If Codecov did not locate your files, please review https://docs.codecov.com/docs/supported-report-formats
[29](https://github.com/GazzolaLab/PyElastica/runs/6696748680?check_suite_focus=true#step:13:30)
[2022-06-01T19:50:24.865Z] ['info'] => Found 1 possible coverage files:
[30](https://github.com/GazzolaLab/PyElastica/runs/6696748680?check_suite_focus=true#step:13:31)
  coverage.xml
[31](https://github.com/GazzolaLab/PyElastica/runs/6696748680?check_suite_focus=true#step:13:32)
[2022-06-01T19:50:24.865Z] ['info'] Processing /home/runner/work/PyElastica/PyElastica/coverage.xml...
[32](https://github.com/GazzolaLab/PyElastica/runs/6696748680?check_suite_focus=true#step:13:33)
[2022-06-01T19:50:24.872Z] ['info'] Detected GitHub Actions as the CI provider.
[33](https://github.com/GazzolaLab/PyElastica/runs/6696748680?check_suite_focus=true#step:13:34)
[2022-06-01T19:50:24.875Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=github-action-3.1.0-uploader-0.2.3&token=*******&branch=80_node_to_element_vel_fix&build=2422940027&build_url=https%3A%2F%2Fgithub.com%2FGazzolaLab%2FPyElastica%2Factions%2Fruns%2F2422940027&commit=376ece21b204b4382f31b352f6d992878b28da02&job=CI&pr=98&service=github-actions&slug=GazzolaLab%2FPyElastica&name=&tag=&flags=&parent=
[34](https://github.com/GazzolaLab/PyElastica/runs/6696748680?check_suite_focus=true#step:13:35)
[2022-06-01T19:50:25.491Z] ['info'] https://codecov.io/github/GazzolaLab/PyElastica/commit/376ece21b204b4382f31b352f6d992878b28da02
[35](https://github.com/GazzolaLab/PyElastica/runs/6696748680?check_suite_focus=true#step:13:36)
https://storage.googleapis.com/codecov/v4/raw/2022-06-01/0EAE7D8E6F10801B0C4E3F2654FD1936/376ece21b204b4382f31b352f6d992878b28da02/7ac7138e-0980-41b1-9383-382c82fc4976.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=GOOG1EKKHVKCKHW7KBCGM7IHR55T63V2PAVJWLVFNITJHDU5G6R5IRN3LMWJA%2F20220601%2FUS%2Fs3%2Faws4_request&X-Amz-Date=20220601T195025Z&X-Amz-Expires=10&X-Amz-SignedHeaders=host&X-Amz-Signature=70370a31d78864457ed29b92280e54da7638f6b14bbb5c235d47f1e9431043de
[36](https://github.com/GazzolaLab/PyElastica/runs/6696748680?check_suite_focus=true#step:13:37)
[2022-06-01T19:50:25.492Z] ['info'] Uploading...
[37](https://github.com/GazzolaLab/PyElastica/runs/6696748680?check_suite_focus=true#step:13:38)
[2022-06-01T19:50:25.680Z] ['info'] {"status":"success","resultURL":"https://codecov.io/github/GazzolaLab/PyElastica/commit/376ece21b204b4382f31b352f6d992878b28da02"}
```

**Review by armantekinalp — APPROVED** [review]
LGTM

**Pull request merged**
