### PR TITLE
Magnetic elastica

### PR DESCRIPTION
**Pull request by armantekinalp**
This PR adds magnetic rod features to PyElastica

- Magnetic rod, which is derived from a Cosserat Rod is implemented.
- Two new forcing classes are added in order to actuate magnetic rod under constant and rotating magnetic field.
- Unit test cases and documentations are added.
- Magnetic rod implementation is validated by comparing with [analytical solution](https://doi.org/10.1016/j.jmps.2020.104045).
- In order to demonstrate deformations of magnetic rod under the rotating magnetic field, a magnetic cilia carpet example is added based on this [paper](https://www.nature.com/articles/s41467-020-16458-4).

### CODE REVIEW

**Comment by skim0119** [comment]
I'm gonna go over this PR later. I don't think it is urgent for `0.2.3`, so I changed the base to `0.3.0`.

**Comment by skim0119** [comment]
@armantekinalp @bhosale2 Did we decide to put these updates in PyElastica repo?

**Comment by armantekinalp** [comment]
We will have a separate repo for magnetism. However, we need to do code refactoring in PyElastica end. We can cancel this PR.

**Comment by skim0119** [comment]
@armantekinalp Can you make another PR with the necessary changes cherry-picked?

**Comment by bhosale2** [comment]
@armantekinalp let's finalize the consensus on this and close the PR.

**Pull request closed without merging**
